pull_request_rules:
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - "status-success=Build (jdk8)"
      - "status-success=Build (jdk11)"
      - "status-success=Build (jdk14)"
    actions:
      merge:
        method: merge
