name: Scala

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Starting up Pulsar 🐳"
        run: docker-compose up -d

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: nixbuild/nix-quick-install-action@v2

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v6
        with:
          name: neutron
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Run with JDK8 🚀"
        run: nix-shell --argstr java jdk8 --run "sbt ++ 'test;makeSite;it:test'"

      - name: "Run with JDK11 🚀"
        run: nix-shell --argstr java jdk11 --run "sbt ++ 'test;makeSite;it:test'"

      - name: "Run with JDK14 🚀"
        run: nix-shell --argstr java jdk14 --run "sbt ++ 'test;makeSite;it:test'"

      - name: "Shutting down Pulsar 🐳"
        run: docker-compose down
