name: Microsite
on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v2.3.2"
        with:
          fetch-depth: 0 # fetch all branches & tags
      - name: "Install Nix ❄️"
        uses: "cachix/install-nix-action@v9"
      - name: "Install SSH 🔑 for GH pages"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: git config --global user.email "neutron-site-bot@chatroulette.com"
      - run: git config --global user.name "neutron-site-bot"
      - name: "Build microsite 🚧"
        run: "nix-shell --run \"sbt ghpagesPushSite\""
