name: sbt-nix-derivation

on:
  pull_request:
    paths:
      - "pkgs.nix"
      - "sbt.nix"

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: nixbuild/nix-quick-install-action@v2

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v6
        with:
          name: neutron
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Build sbt derivation with JDK8 🚀"
        run: nix-build --argstr java jdk8 sbt.nix | cachix push neutron

      - name: "Build sbt derivation with JDK11 🚀"
        run: nix-build --argstr java jdk11 sbt.nix | cachix push neutron

      - name: "Build sbt derivation with JDK14 🚀"
        run: nix-build --argstr java jdk14 sbt.nix | cachix push neutron
