name: sbt-nix-derivation

on:
  push:
    branches:
      - master
    paths:
      - "nix/pkgs.nix"
      - "nix/sbt.nix"

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    env:
      - CACHIX_SIGNING_KEY: "${{ secrets.CACHIX_SIGNING_KEY }}"
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: nixbuild/nix-quick-install-action@v2

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v6
        with:
          name: neutron
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Build sbt derivation with JDK8 🚀"
        run: nix-build --argstr java jdk8 nix/sbt.nix | cachix push neutron

      - name: "Build sbt derivation with JDK11 🚀"
        run: nix-build --argstr java jdk11 nix/sbt.nix | cachix push neutron

      - name: "Build sbt derivation with JDK14 🚀"
        run: nix-build --argstr java jdk14 nix/sbt.nix | cachix push neutron
